"""Build the dataset: truth → background → evidence corpora → answer key → evaluation sheets."""

from __future__ import annotations

import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from northstar import oracle, sla
from northstar.artifacts import Artifact
from northstar.export.csv import to_csv
from northstar.export.yaml import dump
from northstar.factories import Background, build_background
from northstar.generators import generate_evidence
from northstar.model import Truth, load_truth

GENERATED = "GENERATED by `northstar build` — do not edit; edit truth/ and rebuild."
# The build owns exactly these paths under the output directory, and nothing else.
OWNED = ("evidence", "evidence-variants", "answer-key", "evaluation", "DATASET.md")


class IncoherentTruthError(RuntimeError):
    """A scenario's hand-authored expectation does not follow from truth + evidence."""


@dataclass
class Dataset:
    truth: Truth
    background: Background
    artifacts: list[Artifact]
    corpora: dict[str, list[Artifact]]
    results: dict[str, dict[str, Any]]


def assemble(truth_dir: Path, seed: int, scale: str) -> Dataset:
    truth = load_truth(truth_dir)
    bg = build_background(truth, seed, scale)
    artifacts = generate_evidence(truth, bg, seed)
    corpora = {
        name: [a for a in artifacts if a.id not in spec.exclude]
        for name, spec in truth.corpora.items()
    }
    results: dict[str, dict[str, Any]] = {}
    problems: list[str] = []
    for s in truth.scenarios:
        corpus = corpora[s.corpus]
        available = oracle.available_keys(corpus)
        if s.kind == "discount_decision":
            result = oracle.decide(truth, s, available)
        elif s.kind == "credit_decision":
            result = oracle.decide_credit(truth, s, available)
        elif s.kind == "sla_decision":
            result = sla.decide_sla(truth, s, available)
        elif s.kind == "fact_selection":
            result = oracle.select_facts(truth, s, available)
        elif s.kind == "provenance":
            result = oracle.trace_provenance(truth, s, corpus)
        else:
            result = oracle.resolve_identity(truth, s)
        problems += [f"{s.id} {p}" for p in oracle.check(truth, s, result)]
        results[s.id] = result
    if problems:
        raise IncoherentTruthError("\n".join(problems))
    return Dataset(truth, bg, artifacts, corpora, results)


def write(ds: Dataset, out: Path, seed: int, scale: str) -> None:
    out.mkdir(parents=True, exist_ok=True)
    for name in OWNED:
        target = out / name
        if target.is_dir():
            shutil.rmtree(target)
        elif target.exists():
            target.unlink()

    for name, arts in ds.corpora.items():
        root = out / "evidence" if name == "base" else out / "evidence-variants" / name
        for a in arts:
            _write(root / a.path, a.content)
        _write(
            root / "MANIFEST.yaml",
            dump(
                {
                    "corpus": name,
                    "description": ds.truth.corpora[name].description,
                    "organization": ds.truth.organization.name,
                    "artifacts": [
                        {
                            "id": a.id,
                            "path": a.path,
                            "source_system": a.source_system,
                            "description": a.description,
                        }
                        for a in arts
                    ],
                },
                header=GENERATED,
            ),
        )

    key = out / "answer-key"
    note = GENERATED + "\nANSWER KEY — never load into Utopia or any system under test."
    _write(key / "expected-results.yaml", dump(list(ds.results.values()), header=note))
    _write(
        key / "evidence-map.yaml",
        dump(
            [
                {
                    "artifact": a.id,
                    "path": a.path,
                    "supports": list(a.supports),
                    "asserts": list(a.asserts),
                    "mentions": list(a.mentions),
                }
                for a in ds.artifacts
            ],
            header=note + "\nsupports = authoritative evidence; mentions = hearsay/precedent.",
        ),
    )
    _write(key / "temporal-facts.yaml", dump(_temporal_facts(ds.truth), header=note))
    _write(key / "background.yaml", dump(_background_manifest(ds.background), header=note))

    _write(out / "evaluation" / "fact-checklist.csv", _fact_checklist(ds))
    _write(out / "evaluation" / "scenario-scorecard.csv", _scorecard(ds))
    _write(out / "DATASET.md", _dataset_card(ds, seed, scale))


def build(truth_dir: Path, out: Path, seed: int, scale: str) -> Dataset:
    ds = assemble(truth_dir, seed, scale)
    write(ds, out, seed, scale)
    return ds


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")


def _temporal_facts(t: Truth) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for p in t.policies:
        for b in p.bands:
            rows.append(
                {
                    "fact": f"{b.role} discount authority",
                    "source": p.id,
                    "min_exclusive": b.min_exclusive,
                    "max_inclusive": b.max_inclusive,
                    "valid_from": p.valid_from,
                    "valid_to": p.valid_to,
                }
            )
    for c in t.contracts:
        rows.append(
            {
                "fact": f"contract {c.id} in force",
                "source": c.id,
                "valid_from": c.valid_from,
                "valid_to": c.valid_to,
            }
        )
    for x in t.exceptions:
        rows.append(
            {
                "fact": f"{x.customer} max discount on {x.product}",
                "source": x.id,
                "value": x.maximum_discount,
                "supersedes": x.supersedes,
                "valid_from": x.valid_from,
                "valid_to": x.valid_to,
            }
        )
    return rows


def _background_manifest(bg: Background) -> dict[str, Any]:
    return {
        "note": "Generated noise around the truth. Policy-consistent; not part of any scenario.",
        "customers": [c.id for c in bg.customers],
        "employees": [e.id for e in bg.employees],
        "products": [p.id for p in bg.products],
        "orders": len(bg.orders),
        "discount_requests": len(bg.discount_requests),
        "owners_assigned_to_truth_customers": bg.truth_customer_owners,
    }


def _fact_checklist(ds: Dataset) -> str:
    rows = []
    for f in ds.truth.facts:
        stated_in = [a.id for a in ds.artifacts if f.id in a.asserts]
        rows.append(
            [f.id, f.statement, f.kind, "YES" if f.owm_needed else "", ";".join(stated_in), "", ""]
        )
    return to_csv(
        ["fact_id", "fact", "kind", "owm_needed", "stated_in", "utopia_result", "notes"], rows
    )


def _scorecard(ds: Dataset) -> str:
    rows = []
    for s in ds.truth.scenarios:
        r = ds.results[s.id]
        if s.kind in ("discount_decision", "credit_decision", "sla_decision"):
            expected = r["decision"]["outcome"]
        elif s.kind == "fact_selection":
            expected = "; ".join(f"{p['as_of']}={p['exception']}" for p in r["probes"])
        elif s.kind == "provenance":
            expected = f"basis {r['basis']} under {r['contract']}"
        else:
            expected = "; ".join(f"{k}={'/'.join(v)}" for k, v in r["same_as"].items())
        rows.append([s.id, s.title, s.corpus, s.question, expected, "", "", ""])
    return to_csv(
        [
            "scenario",
            "title",
            "corpus",
            "question",
            "expected",
            "utopia_answer",
            "owm_answer",
            "notes",
        ],
        rows,
    )


def _dataset_card(ds: Dataset, seed: int, scale: str) -> str:
    lines = [
        "# Northstar evidence dataset",
        "",
        f"_{GENERATED}_",
        "",
        f"- Seed: `{seed}` · Scale: `{scale}`",
        f"- Artifacts in base corpus: {len(ds.corpora['base'])}",
        f"- Background: {len(ds.background.customers)} customers, "
        f"{len(ds.background.employees)} employees, {len(ds.background.products)} products, "
        f"{len(ds.background.orders)} orders, "
        f"{len(ds.background.discount_requests)} discount requests, "
        f"{len(ds.background.invoices)} invoices, "
        f"{len(ds.background.credit_requests)} credit requests",
        "",
        "## Load into the knowledge foundation",
        "",
        "| Corpus | Directory | Used by |",
        "|---|---|---|",
    ]
    for name in ds.corpora:
        where = "evidence/" if name == "base" else f"evidence-variants/{name}/"
        used = ", ".join(s.id for s in ds.truth.scenarios if s.corpus == name)
        lines.append(f"| {name} | `{where}` | {used} |")
    lines += [
        "",
        "## Do not load",
        "",
        "- `answer-key/` — expected results, the evidence map and the temporal facts.",
        "- `evaluation/` — the sheets you fill in while running the experiment.",
    ]
    return "\n".join(lines) + "\n"
